

public enum ClaseLexica {
 IDEN, NUMENT, NUMREAL, CADENA, EOF, MAS, MENOS, POR, DIV,
 SEP, MOD, MENOR, MAYOR, MENORIGUAL, MAYORIGUAL, IGUALDAD,
 IGUAL, DISTINTO, PAPER, PCIERRE, PYC, CORAPER, CORCIERRE,
 LLAVEAPER, LLAVECIERRE, PUNTO, COMA, FLECHA, AMPERSAND, INT,
 REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC,
 IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD,
 ARRAY, OF, POINTER, NEW , DELETE, READ, WRITE, NL, VAR, TYPE
}