/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int donde = 8;
  int evalua = 9;
  int identificador = 10;
  int numeroEntero = 11;
  int numeroReal = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"donde\"",
    "\"evalua\"",
    "<identificador>",
    "<numeroEntero>",
    "<numeroReal>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
