
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 21 02:54:45 BST 2021
//----------------------------------------------------

package constructorAST_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LLAVEAPER = 20;
  public static final int SEP = 6;
  public static final int DISTINTO = 14;
  public static final int POR = 4;
  public static final int PCIERRE = 16;
  public static final int PAPER = 15;
  public static final int INT = 26;
  public static final int ARRAY = 46;
  public static final int WRITE = 52;
  public static final int DELETE = 50;
  public static final int NUMENT = 57;
  public static final int NOT = 32;
  public static final int MENORIGUAL = 10;
  public static final int AND = 30;
  public static final int IGUAL = 13;
  public static final int RECORD = 45;
  public static final int TYPE = 55;
  public static final int IGUALDAD = 12;
  public static final int OR = 31;
  public static final int BOOL = 28;
  public static final int CALL = 44;
  public static final int DIV = 5;
  public static final int IF = 37;
  public static final int AMPERSAND = 25;
  public static final int ENDWHILE = 43;
  public static final int OF = 47;
  public static final int MAYORIGUAL = 11;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 21;
  public static final int TRUE = 34;
  public static final int CORAPER = 18;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int CADENA = 59;
  public static final int MENOS = 3;
  public static final int NULL = 33;
  public static final int MENOR = 8;
  public static final int MOD = 7;
  public static final int NUMREAL = 58;
  public static final int REAL = 27;
  public static final int MAYOR = 9;
  public static final int FLECHA = 24;
  public static final int ENDIF = 40;
  public static final int ELSE = 39;
  public static final int PUNTO = 22;
  public static final int NL = 53;
  public static final int READ = 51;
  public static final int IDEN = 56;
  public static final int WHILE = 41;
  public static final int THEN = 38;
  public static final int PROC = 36;
  public static final int STRING = 29;
  public static final int CORCIERRE = 19;
  public static final int POINTER = 48;
  public static final int FALSE = 35;
  public static final int VAR = 54;
  public static final int DO = 42;
  public static final int PYC = 17;
  public static final int MAS = 2;
}

