
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 24 22:35:41 BST 2021
//----------------------------------------------------

package analizadorSintacticoAscendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LLAVEAPER = 24;
  public static final int SEP = 10;
  public static final int DISTINTO = 18;
  public static final int POR = 8;
  public static final int PCIERRE = 20;
  public static final int PAPER = 19;
  public static final int INT = 30;
  public static final int ARRAY = 50;
  public static final int WRITE = 56;
  public static final int DELETE = 54;
  public static final int NUMENT = 3;
  public static final int NOT = 36;
  public static final int MENORIGUAL = 14;
  public static final int AND = 34;
  public static final int IGUAL = 17;
  public static final int RECORD = 49;
  public static final int TYPE = 59;
  public static final int OR = 35;
  public static final int IGUALDAD = 16;
  public static final int BOOL = 32;
  public static final int CALL = 48;
  public static final int DIV = 9;
  public static final int IF = 41;
  public static final int AMPERSAND = 29;
  public static final int ENDWHILE = 47;
  public static final int OF = 51;
  public static final int MAYORIGUAL = 15;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 25;
  public static final int TRUE = 38;
  public static final int CORAPER = 22;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int CADENA = 5;
  public static final int MENOS = 7;
  public static final int NULL = 37;
  public static final int MENOR = 12;
  public static final int MOD = 11;
  public static final int NUMREAL = 4;
  public static final int REAL = 31;
  public static final int MAYOR = 13;
  public static final int FLECHA = 28;
  public static final int ENDIF = 44;
  public static final int ELSE = 43;
  public static final int PUNTO = 26;
  public static final int NL = 57;
  public static final int READ = 55;
  public static final int IDEN = 2;
  public static final int WHILE = 45;
  public static final int THEN = 42;
  public static final int PROC = 40;
  public static final int STRING = 33;
  public static final int CORCIERRE = 23;
  public static final int POINTER = 52;
  public static final int FALSE = 39;
  public static final int VAR = 58;
  public static final int DO = 46;
  public static final int PYC = 21;
  public static final int MAS = 6;
}

