package analizadorLexico;

public enum ClaseLexica {
 SEPARADOR, PUNTOYCOMA, MAS, MENOS, POR, DIV, IGUAL, MENOR,
 MAYOR, MENORIGUAL, MAYORIGUAL, IGUALDAD, DISTINTO, PAPERTURA, 
 PCIERRE, VARIABLE, ENT, NUMREAL, EOF, INT, REAL, BOOL, TRUE,
 FALSE, AND, OR, NOT
}
