/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package analizadorSintactico;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int numeroEntero = 5;
  int parteDecimal = 6;
  int parteExponencial = 7;
  int numeroReal = 8;
  int cadena = 9;
  int int_pr = 12;
  int real = 13;
  int bool = 14;
  int string = 15;
  int and = 16;
  int or = 17;
  int not = 18;
  int null_pr = 19;
  int true_pr = 20;
  int false_pr = 21;
  int proc = 22;
  int if_pr = 23;
  int then = 24;
  int else_pr = 25;
  int endif = 26;
  int while_pr = 27;
  int do_pr = 28;
  int endwhile = 29;
  int call = 30;
  int record = 31;
  int array = 32;
  int of = 33;
  int pointer = 34;
  int new_pr = 35;
  int delete = 36;
  int read = 37;
  int write = 38;
  int nl = 39;
  int var = 40;
  int type = 41;
  int suma = 42;
  int resta = 43;
  int multiplicacion = 44;
  int division = 45;
  int sep = 46;
  int modulo = 47;
  int menor = 48;
  int mayor = 49;
  int menorIgual = 50;
  int mayorIgual = 51;
  int igualdad = 52;
  int distinto = 53;
  int pApert = 54;
  int pCierre = 55;
  int pyc = 56;
  int igual = 57;
  int corApert = 58;
  int corCierre = 59;
  int llaveAper = 60;
  int llaveCierre = 61;
  int punto = 62;
  int flecha = 63;
  int coma = 64;
  int ampersand = 65;
  int identificador = 66;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<numeroEntero>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<numeroReal>",
    "<cadena>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"->\"",
    "\",\"",
    "\"&\"",
    "<identificador>",
  };

}
