
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Apr 26 12:29:56 CEST 2020
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int NUM = 12;
  public static final int COMA = 10;
  public static final int MENOS = 3;
  public static final int PAP = 6;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int ID = 13;
  public static final int DIV = 5;
  public static final int IGUAL = 11;
  public static final int EVALUA = 9;
  public static final int error = 1;
  public static final int PCIERRE = 7;
  public static final int DONDE = 8;
}

